@echo off
setlocal enabledelayedexpansion

REM 执行查询并直接将输出存储在变量中，使用 --format=csv 并去掉标题行
for /f "usebackq tokens=*" %%i in (`bq query --location=asia-northeast1 --nouse_legacy_sql --format=csv --quiet "WITH FABKLS AS (SELECT DISTINCT FABKL FROM `lixil-datalake.an1_SAP_CFIN.T001W`), TFACS_YEAR AS (SELECT IDENT, JAHR AS YEAR, [STRUCT('01' AS MONTH, MON01 AS MONTH_FLAGS), STRUCT('02' AS MONTH, MON02 AS MONTH_FLAGS), STRUCT('03' AS MONTH, MON03 AS MONTH_FLAGS), STRUCT('04' AS MONTH, MON04 AS MONTH_FLAGS), STRUCT('05' AS MONTH, MON05 AS MONTH_FLAGS), STRUCT('06' AS MONTH, MON06 AS MONTH_FLAGS), STRUCT('07' AS MONTH, MON07 AS MONTH_FLAGS), STRUCT('08' AS MONTH, MON08 AS MONTH_FLAGS), STRUCT('09' AS MONTH, MON09 AS MONTH_FLAGS), STRUCT('10' AS MONTH, MON10 AS MONTH_FLAGS), STRUCT('11' AS MONTH, MON11 AS MONTH_FLAGS), STRUCT('12' AS MONTH, MON12 AS MONTH_FLAGS)] AS MONTH_INFO FROM `lixil-datalake.an1_SAP_LHT2nd.TFACS`), TFACS_MONTH AS (SELECT IDENT, CONCAT(YEAR, MONTH_INFO.MONTH) AS YEAR_MONTH, SPLIT(MONTH_INFO.MONTH_FLAGS, '') AS MONTH_FLAGS FROM TFACS_YEAR CROSS JOIN UNNEST(TFACS_YEAR.MONTH_INFO) AS MONTH_INFO), TFACS_DAY AS (SELECT IDENT, CONCAT(YEAR_MONTH, LPAD(CAST((DAY + 1) AS STRING), 2, '0')) AS YEAR_MONTH_DAY, CAST(DAY_FLAGS AS INT64) AS DAY_FLAGS FROM TFACS_MONTH CROSS JOIN UNNEST(TFACS_MONTH.MONTH_FLAGS) AS DAY_FLAGS WITH OFFSET AS DAY WHERE IDENT IN (SELECT FABKL FROM FABKLS) AND DAY_FLAGS='1') SELECT YEAR_MONTH_DAY FROM TFACS_DAY WHERE IDENT= 'Z5';"`) do (
    echo %%i
)

pause
endlocal
